// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALJePDcd6EucycPjcHgE3amDqDCbqmjt4',
    appId: '1:916691300216:web:ddee0f78fe2770b054a28d',
    messagingSenderId: '916691300216',
    projectId: 'gadgetgallore-46198',
    authDomain: 'gadgetgallore-46198.firebaseapp.com',
    storageBucket: 'gadgetgallore-46198.appspot.com',
    measurementId: 'G-MS3G0Q6GK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcwHSbF43VAUTMupD7WbTrs0hta7H8B_0',
    appId: '1:916691300216:android:1e7ed5089b3b001a54a28d',
    messagingSenderId: '916691300216',
    projectId: 'gadgetgallore-46198',
    storageBucket: 'gadgetgallore-46198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfSS1gymjtGOZW0LGKU2Bt_2aI9W_EdgI',
    appId: '1:916691300216:ios:405fc6389b283ae554a28d',
    messagingSenderId: '916691300216',
    projectId: 'gadgetgallore-46198',
    storageBucket: 'gadgetgallore-46198.appspot.com',
    iosBundleId: 'com.example.gadgetgallore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfSS1gymjtGOZW0LGKU2Bt_2aI9W_EdgI',
    appId: '1:916691300216:ios:8c62cbcb7d8974f054a28d',
    messagingSenderId: '916691300216',
    projectId: 'gadgetgallore-46198',
    storageBucket: 'gadgetgallore-46198.appspot.com',
    iosBundleId: 'com.example.gadgetgallore.RunnerTests',
  );
}
